export const EVENTS = {
  //Actions related to X
  GET_HOME_DATA: "home/GET_HOME_DATA",
  GET_HOME_DATA_SUCCESS: "home/GET_HOME_DATA_SUCCESS",
  GET_HOME_DATA_FAILURE: "home/GET_HOME_DATA_FAILURE",
  GET_MORE_HOME_DATA: "home/GET_MORE_HOME_DATA",
  GET_MORE_HOME_DATA_SUCCESS: "home/GET_MORE_HOME_DATA_SUCCESS",
  GET_MORE_HOME_DATA_FAILURE: "home/GET_HOME_DATA_FAILURE",
} as const;
